spring:
  application:
    name: MemberProvider
#  cloud:
    # 网卡信息
#    inetutils:
#      preferred-networks: 192.168.0.255
server:
  port: 8081
eureka:
  instance:
    hostname: localhost
    # 这个不配置一直找不的注册中心
    prefer-ip-address: true
    #指定跳转地址
    #status-page-url: https://www.baidu.com
#    instance-id: 192.168.0.100:${server.port}
  client:
    service-url:
#      defaultZone: http://tom:123456@${eureka.instance.hostname}:8761/eureka/,http://tom:123456@${eureka.instance.hostname}:8762/eureka/
      #单机方式
      defaultZone: http://tom:123456@${eureka.instance.hostname}:8761/eureka/
